var InitJSVersion="Jan_28_2021_V1",g_EnableBorderInTemplate=false,g_EnableAutomationFlag=false,m_objParentWindow=null,g_objScriptLoader=null,g_objPB=null,g_objFL=null,g_URLPathSeperator="",g_objLoger,g_CommandArgs={},g_LoadingMsg="Loading Please wait...",m_sTimerMsg,m_CurTimerToWait,m_CurTimerId,g_enabledualmonitor=false,PLAYSTATE={NONE:"NONE",PLAYING:"PLAYING",PAUSED:"PAUSED",STOPPED:"STOPPED",READY:"READY",PLAYENDED:"PLAYENDED",ERROR:"ERROR",BUSY:"BUSY",NOTINITIALIZED:"NOT INITIALIZED",INITIALIZED:"INITIALIZED"};
window.onload=function(){Initialize()};
function Initialize(){try{g_CriticalErrorCode=CRITICALERRORS.NONE;g_LauncherErrorCode=LAUNCHERRORS.NONE;g_LoadingMsg=document.getElementById("LoadMsg").innerHTML;SetParentWindow();document.body.style.cursor="wait";if(ReadCmdlineArgs()==false)throw"Error @ ReadCmdlineArgs";InitializeLoger();if(g_IdentifyTypeOfBrowser()==false)throw g_LauncherErrorCode=LAUNCHERRORS.BROWSERNOTSUPPORTED,"Error @ g_IdentifyTypeOfBrowser";if(g_IdentifyTypeOfDevice()===false)throw"Error @ g_IdentifyTypeOfDevice";if(g_IsBrowserHTML5Compatible()==
false)if(g_iLegacyKey==17091950)BROWSER.LEGACY=true,g_inline="inline";else throw g_LauncherErrorCode=LAUNCHERRORS.CANVASNOTSUPPORTED,"Error @ g_IdentifyTypeOfBrowser, g_iLegacyKey!=17091950";g_WriteToLog("PlayerHtm","Initialize","BROWSER.LEGACY",BROWSER.LEGACY,LOG.TRACE);g_URLPathSeperator=document.URL.lastIndexOf("\\")==-1?"/":"\\";if(FullScreenLauchTest()==false)throw"Error @ FullScreenLauchTest";}catch(b){if(g_CriticalErrorCode==CRITICALERRORS.NONE)g_CriticalErrorCode=CRITICALERRORS.EX_INITIALIZE;
g_WriteToLog("PlayerHtm","Initialize",b,"",LOG.EXCEPTION);g_CriticalError()}}
function StartFileLoadingAcitvities(){var b=true;try{g_objScriptLoader=new clsScriptLoader,g_objScriptLoader.onLoadComplete=Files_onLoadComplete,g_WriteToLog("PlayerHtm","Initialize","","Loading > init/files.js",LOG.TRACE),g_objScriptLoader.Load("init/files.js")}catch(f){if(g_CriticalErrorCode==CRITICALERRORS.NONE)g_CriticalErrorCode=CRITICALERRORS.EX_INITIALIZE;b=false;g_WriteToLog("PlayerHtm","StartFileLoadingAcitvities",f,"",LOG.EXCEPTION)}return b}
function ReadCmdlineArgs(){var b=true;try{var f="",f=window.location.hash;if(f!=""&&(f=f.substring(1,f.length),ReadCmdline(f)==false))throw"Error @ ReadCmdline";}catch(a){if(g_CriticalErrorCode==CRITICALERRORS.NONE)g_CriticalErrorCode=CRITICALERRORS.EX_LAUNCH;b=false;g_WriteToLog("PlayerHtm","ReadCmdlineArgs",a,"",LOG.EXCEPTION)}return b}
function ReadCmdline(b){var f=true;try{for(var a=b.split(/&|#/),h=a.length;h>0;){var c=a[h-1],c=c.split("=");V=c[1];c=c[0];if(c.toUpperCase().indexOf("VSQ")!=-1)g_CommandArgs[CMDARGS.VARIATIONPATHS]==void 0&&(g_CommandArgs[CMDARGS.VARIATIONPATHS]=[]),b={},b.TPSID="K"+c.toUpperCase().split("VSQ")[1],b.Value=V,g_CommandArgs[CMDARGS.VARIATIONPATHS].push(b);else if(c.toUpperCase().indexOf("VSH")!=-1){g_CommandArgs[CMDARGS.VARIATIONSHIDE]==void 0&&(g_CommandArgs[CMDARGS.VARIATIONSHIDE]=[]);var b=[],b=
V.split(","),d;for(d in b)g_CommandArgs[CMDARGS.VARIATIONSHIDE]["K"+b[d]]="1"}else g_CommandArgs[c]=V;h--}}catch(e){f=false,g_WriteToLog("PlayerHtm","ReadCmdline",e,"",LOG.EXCEPTION)}return f}function SetParentWindow(){try{if(window.dialogArguments)try{m_objParentWindow=window.dialogArguments}catch(b){}if(window.opener)try{m_objParentWindow=window.opener}catch(f){}}catch(a){g_WriteToLog("PlayerHtm","SetParentWindow",a,"",LOG.EXCEPTION)}}
function GetErrorMessage(){var b="";try{if(m_objParentWindow!=null)switch(g_LauncherErrorCode){case LAUNCHERRORS.CANVASNOTSUPPORTED:b=m_objParentWindow.document.getElementById("HTML5NotSupported").innerText;break;case LAUNCHERRORS.BROWSERNOTSUPPORTED:b=m_objParentWindow.document.getElementById("InValidBrowser").innerText;break;default:b=m_objParentWindow.document.getElementById("CriticalError").innerText}else switch(g_LauncherErrorCode){case LAUNCHERRORS.CANVASNOTSUPPORTED:b="This browser does not support HTML5 features. Use the latest HTML5 compatible browser..";
break;case LAUNCHERRORS.BROWSERNOTSUPPORTED:b="This epiLearn is certified for IE, Chrome, Safari, Firefox, Opera..";break;default:b="Failed to launch epiLearn. Contact your system administrator for support.."}g_CriticalErrorCode!=CRITICALERRORS.NONE&&(b+="\n\nErrorCode : "+g_CriticalErrorCode)}catch(f){b="Failed to launch epiLearn. Contact your system administrator for support..."}return b}function g_WriteToLog(b,f,a,h,c){try{g_objLoger!=null&&g_objLoger.Log(b,f,a,h,c)}catch(d){}}
function objFileLoader_onLoadComplete(b){try{if(b==false)throw g_CriticalErrorCode=CRITICALERRORS.OBJFL_LOADCOMPLETE_FALSE,"objFileLoader_onLoadComplete bSuccess=false ";g_objScriptLoader.onLoadComplete=null;LoadEpiLearn()}catch(f){if(g_CriticalErrorCode==CRITICALERRORS.NONE)g_CriticalErrorCode=CRITICALERRORS.EX_OBJFL_LOADCOMPLETE;g_WriteToLog("PlayerHtm","objFileLoader_onLoadComplete",f,"",LOG.EXCEPTION);g_CriticalError()}}
function InitializeLoger(){try{g_objLoger=new clsLoger;g_CommandArgs[CMDARGS.LOG]!=void 0&&(g_EnableLoger=true,g_LogTypes="");g_objLoger.PlainLog=g_EnablePlainLogs;g_objLoger.Enable=g_EnableLoger;g_objLoger.EnableAlertAtLoger=g_EnableAlertAtLoger;if(g_LogTypes!="")if(g_LogTypes=="")for(i in LOG)g_objLoger.LogTypes.push(LOG[i]);else{var b=g_LogTypes.split("|");for(i in b)g_objLoger.LogTypes.push(b[i])}if(g_ClassTypes!="")for(i in b=g_ClassTypes.split("|"),b)g_objLoger.ClassTypes.push(b[i]);g_objLoger.Initialize("HTML5 epiLearn Logs")}catch(f){}}
function Files_onLoadComplete(b){try{if(b==false)throw g_CriticalErrorCode=CRITICALERRORS.FILES_LOADCOMPLETE_FALSE,"Files_onLoadComplete bSuccess=false";if(window.files_json==void 0)throw g_CriticalErrorCode=CRITICALERRORS.FILES_JSON_MISSING,"Files_onLoadComplete files_json=undefined";g_CommandArgs[CMDARGS.SURL]!=void 0&&(g_StaticURL=g_CommandArgs[CMDARGS.SURL]);g_objFL=new clsFileLoader;g_objFL.onLoadComplete=objFileLoader_onLoadComplete;if(g_objFL.Initialize()==false)throw g_CriticalErrorCode=CRITICALERRORS.OBJFL_INITIALIZE_FALSE,
"Error @ g_objFL.Initialize";if(g_objFL.Load()==false)throw g_CriticalErrorCode=CRITICALERRORS.OBJFL_LOAD_FALSE,"Error @ g_objFL.Load";}catch(f){if(g_CriticalErrorCode==CRITICALERRORS.NONE)g_CriticalErrorCode=CRITICALERRORS.EX_FILES_LOADCOMPLETE;g_WriteToLog("PlayerHtm","Files_onLoadComplete",f,"",LOG.EXCEPTION);g_CriticalError()}}
function FullScreenLauchTest(){var b=true;try{var f=true;g_CommandArgs[CMDARGS.FULLSCREEN]!=void 0&&g_CommandArgs[CMDARGS.FULLSCREEN]=="0"&&(f=false);switch(g_CommandArgs[CMDARGS.LAUNCHSOURCE]){case LAUNCHSOURCETYPE.PRESENTATIONEDITOR:f=false;break;case LAUNCHSOURCETYPE.PRESENTATIONOUTPUT:f=false}if(f==true)if(g_PromptFullScreen==true&&FullScreenSupportAvailable()==true){f="This browser supports full screen view.";m_sTimerMsg="This epiLearn will be launched in normal view in %1 seconds";var a="Full Screen View",
h="Normal View";try{f=m_objParentWindow.document.getElementById("SupportsFullScreen").innerHTML,a=m_objParentWindow.document.getElementById("FullScreenView").innerHTML,h=m_objParentWindow.document.getElementById("NormalView").innerHTML,m_sTimerMsg=m_objParentWindow.document.getElementById("TimerMsg").innerHTML}catch(c){}var d=document.getElementById("LoadMsg"),e="<br/><br/>";e+=f+"<br/><br/>";e+="<button onclick='return ProceedFullScreenView()'>"+a+"</button> &nbsp;&nbsp;&nbsp;&nbsp; ";e+="<button onclick='return ProceedNormalView()'>"+
h+"</button>";e+="<br/><br/>";m_CurTimerToWait=g_TimerFullScreen/1E3;e+="<span id='SpanTimerMsg'>"+m_sTimerMsg.replace("%1",m_CurTimerToWait)+"</span>";d.innerHTML=e;m_CurTimerId=setTimeout(CheckToProceedNormalView,1E3)}else{d=1;try{g_DualMonitor=="1"&&(g_enabledualmonitor=true,d=2)}catch(g){g_WriteToLog("PlayerHtm","FullScreenLauchTest",g,"Ignore",LOG.EXCEPTION)}window.moveTo(0,0);window.resizeTo(screen.availWidth*d,screen.availHeight);setTimeout(StartFileLoadingAcitvities,100)}else setTimeout(StartFileLoadingAcitvities,
100)}catch(k){b=false,g_WriteToLog("PlayerHtm","FullScreenLauchTest",k,"",LOG.EXCEPTION)}return b}function FullScreenSupportAvailable(){var b=false;try{document.documentElement.requestFullscreen?b=true:document.documentElement.msRequestFullscreen?b=true:document.documentElement.mozRequestFullScreen?b=true:document.documentElement.webkitRequestFullscreen&&(b=true)}catch(f){g_WriteToLog("PlayerHtm","FullScreenSupportAvailable",f,"",LOG.EXCEPTION)}return b}
function ProceedFullScreenView(){var b=true;try{clearTimeout(m_CurTimerId),m_CurTimerId=0,document.documentElement.requestFullscreen?document.documentElement.requestFullscreen():document.documentElement.msRequestFullscreen?document.documentElement.msRequestFullscreen():document.documentElement.mozRequestFullScreen?document.documentElement.mozRequestFullScreen():document.documentElement.webkitRequestFullscreen&&document.documentElement.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT),document.getElementById("LoadMsg").style.width=
screen.availWidth-20+"px",setTimeout(StartFileLoadingAcitvities,1)}catch(f){b=false,g_WriteToLog("PlayerHtm","ProceedFullScreenView",f,"",LOG.EXCEPTION)}return b}function ProceedNormalView(){var b=true;try{clearTimeout(m_CurTimerId),m_CurTimerId=0,window.moveTo(0,0),window.resizeTo(screen.availWidth,screen.availHeight),setTimeout(StartFileLoadingAcitvities,1)}catch(f){b=false,g_WriteToLog("PlayerHtm","ProceedNormalView",f,"",LOG.EXCEPTION)}return b}
function CheckToProceedNormalView(){var b=true;try{if(m_CurTimerToWait--,m_CurTimerToWait<=0){if(ProceedNormalView()==false)throw"Error @ CheckToProceedNormalView";}else document.getElementById("SpanTimerMsg").innerHTML=m_sTimerMsg.replace("%1",m_CurTimerToWait),m_CurTimerId=setTimeout(CheckToProceedNormalView,1E3)}catch(f){b=false,g_WriteToLog("PlayerHtm","CheckToProceedNormalView",f,"",LOG.EXCEPTION)}return b}
function clsPlayerBase(b,f){this.ClassName=b!=void 0?b:"";this.ObjectName=f!=void 0?f:"";this.Initialized=this.ID="";this.onPlayComplete=this.onPlayStateChange=this.onLoadComplete=this.onInitComplete=null;this.Log2=function(a,b,c,d,e){try{e=e==void 0?"":e;if(e.description!=void 0)e=e.description;g_WriteToLog(a,b,d==void 0?"":d,e,c)}catch(f){}};this.Log=function(a,b,c,d){try{d=d==void 0?"":d;if(d.description!=void 0)d=d.description;g_WriteToLog(this.ClassName,a,c==void 0?"":c,d,b)}catch(e){}};this.GetUniqueID=
function(){var a="";try{var b=new Date,a=b.getHours()+"_"+b.getMinutes()+"_"+b.getSeconds()+"_"+b.getMilliseconds()+Math.random(),a=a.replace(".","")}catch(c){g_WriteToLog("clsPlayerBase","GetUniqueID","",c,LOG.EXCEPTION)}return a};this.CreateHTMLElement=function(a){var b;try{b=document.createElement(a);b.id=this.GetUniqueID();b.style.position="absolute";b.style.visibility="hidden";b.style.display="none";try{b.style.fontFamily=messages_json.general.common.uifont.text}catch(c){}}catch(d){b=null,g_WriteToLog("clsPlayerBase",
"CreateHTMLElement","",d,LOG.EXCEPTION)}return b};this.CreateTextHolder=function(a){var b;try{b=document.createElement("div");b.id=this.GetUniqueID();b.style.position="absolute";b.style.visibility="visible";b.dir=uid_json.settings.template.rtl;b.style.fontFamily=messages_json.general.common.uifont.text;var c=b,d=true;try{if(a!==void 0&&a.css!==void 0){if(a.css.fs!=void 0)c.style.fontSize=a.css.fs;if(a.css.fw!=void 0)c.style.fontWeight=a.css.fw;if(a.css.fc!=void 0)c.style.color=a.css.fc;if(a.css.ff!=
void 0)c.style.fontFamily=a.css.ff;if(a.css.ta!=void 0)c.style.textAlign=a.css.ta;if(a.css.bgc!=void 0)try{c.style.backgroundColor=a.css.bgc}catch(e){}if(a.css.bg!=void 0)c.style.background=a.css.bg;if(a.css.bgr!=void 0)c.style.backgroundRepeat=a.css.bgr;if(a.css.bw!=void 0)c.style.borderWidth=a.css.bw;if(a.css.bs!=void 0)c.style.borderStyle=a.css.bs;if(a.css.bc!=void 0)c.style.borderColor=a.css.bc;if(a.css.br!=void 0)c.style.borderRadius=a.css.br;if(a.css.btlr!=void 0)c.style.borderTopLeftRadius=
a.css.btlr;if(a.css.btrr!=void 0)c.style.borderTopRightRadius=a.css.btrr;if(a.css.bblr!=void 0)c.style.borderBottomLeftRadius=a.css.bblr;if(a.css.bbrr!=void 0)c.style.borderBottomRightRadius=a.css.bbrr;if(a.css.pd!=void 0)c.style.padding=a.css.pd;if(a.css.pdl!=void 0)c.style.paddingLeft=a.css.pdl;if(a.css.pdr!=void 0)c.style.paddingRight=a.css.pdr;if(a.css.pdt!=void 0)c.style.paddingTop=a.css.pdt;if(a.css.pdb!=void 0)c.style.paddingBottom=a.css.pdb;if(a.css.of!=void 0)c.style.overflow=a.css.of;if(a.css.ofx!=
void 0)c.style.overflowX=a.css.ofx;if(a.css.ofy!=void 0)c.style.overflowY=a.css.ofy;if(a.css.dc!=void 0)c.style.textDecoration=a.css.dc;if(a.css.cr!=void 0)c.style.cursor=a.css.cr;if(a.css.lf!=void 0)c.style.left=a.css.lf;if(a.css.tp!=void 0)c.style.top=a.css.tp;if(a.css.wd!=void 0)c.style.width=a.css.wd;if(a.css.ht!=void 0)c.style.height=a.css.ht;if(a.css.bxs!=void 0)c.style.boxShadow=a.css.bxs}}catch(f){d=false,g_WriteToLog("clsPlayerBase","AssignElmStyles","",f,LOG.EXCEPTION)}if(d==false)throw"error @ AssignElmStyles";
}catch(k){b=null,g_WriteToLog("clsPlayerBase","CreateTextHolder","",k,LOG.EXCEPTION)}return b}}
clsFileLoader=function(){function b(b){var a=true;try{if(b==false)throw"Error in CssFiles_LoadComplete ";d.ResourceLoaded(true,this.FileName);o++;if(o==j&&(d.Log("CssFiles_LoadComplete",LOG.SPECIAL,o,"Loaded CSS files in async-mode"),f()==false))throw"Error @ LoadNonSeqFiles";}catch(c){a=false,d.Log("CssFiles_LoadComplete",LOG.EXCEPTION,"",c)}if(a==false)g_objScriptLoader.onLoadComplete=null,d.onLoadComplete(false)}function f(){var b=true;try{m_NonSeqFiles_ToBeLoaded=files_json.nonseq.length;d.Log("LoadNonSeqFiles",
LOG.SPECIAL,"Loading js files in async-mode",files_json.nonseq.length);for(var c=0;c<files_json.nonseq.length;c++){g_objScriptLoader.onLoadComplete=a;for(var e in files_json.nonseq[c])if(g_objScriptLoader.Load(g_StaticURL+files_json.nonseq[c][e])==false)throw"Error @ g_objScriptLoader.Load";}}catch(f){b=false,d.Log("LoadNonSeqFiles",LOG.EXCEPTION,"",f)}return b}function a(b){var a=true;try{if(b==false)throw"Error in NonSeqFiles_LoadComplete ";d.ResourceLoaded(true,this.FileName);k++;if(k==m_NonSeqFiles_ToBeLoaded)if(d.Log("NonSeqFiles_LoadComplete",
LOG.SPECIAL,k,"Loaded js files in sync-mode"),p=(files_json.seq.yahoo.scripts||[]).concat(files_json.seq.jquery.scripts||[]),n=p.length,n>0){if(d.Log("NonSeqFiles_LoadComplete",LOG.SPECIAL,"Loading js files in sync-mode",n),h(0)==false)throw"Error @ LoadSeqFiles";}else d.onLoadComplete(true)}catch(c){a=false,d.Log("NonSeqFiles_LoadComplete",LOG.EXCEPTION,this.FileName,c)}if(a==false)g_objScriptLoader.onLoadComplete=null,d.onLoadComplete(false)}function h(b){var a=true;try{for(i in p[b])if(g_objScriptLoader.onLoadComplete=
c,g_objScriptLoader.Load(g_StaticURL+p[b][i])==false)throw"Error @ g_objScriptLoader.Load";}catch(e){a=false,d.Log("LoadSeqFiles",LOG.EXCEPTION,"",e)}return a}function c(){var b=true;try{l++,l==n?(d.Log("SeqFiles_LoadComplete",LOG.SPECIAL,l,"Loaded js files in sync-mode"),d.Log("SeqFiles_LoadComplete",LOG.SPECIAL,"","All JS and CSS files loaded"),d.onLoadComplete(true)):h(l)}catch(a){b=false,d.Log("SeqFiles_LoadComplete",LOG.EXCEPTION,"",a)}if(b==false)g_objScriptLoader.onLoadComplete=null,d.onLoadComplete(false)}
clsPlayerBase.call(this,"clsFileLoader");var d=this;this.onLoadComplete=null;this.ScriptFileCount=this.ImagesCount=0;var e=null,g=null,k=0,l=0,n=0,o=0,j=0,p=[],m=[];this.Hide=function(){try{g.style.display="none"}catch(b){d.Log("Hide",LOG.EXCEPTION,"",b)}};this.Initialize=function(){var b=true;try{g=document.getElementById("LoadMsg");g.innerHTML="";g.style.textAlign="center";g.style.width="100%";var a=d.CreateHTMLElement("DIV");a.style.display=g_inline;a.style.visibility="visible";a.style.borderRadius=
"5px";a.style.left="36%";a.style.width="350px";a.style.position="absolute";a.style.padding="10px";a.style.textAlign="center";a.innerHTML=g_LoadingMsg;g.appendChild(a);e=d.CreateHTMLElement("DIV");e.style.display=g_inline;e.style.visibility="visible";e.style.borderRadius="5px";e.style.left="36%";e.style.top="20px";e.style.width="350px";e.style.position="absolute";e.style.padding="10px";g.appendChild(e);g_objPB=new clsProgressBar;g_objPB.Left="10%";g_objPB.Top="50%";g_objPB.Width="300px";g_objPB.Height=
"20px";if(g_objPB.Create(e,a,null,"center")==false)throw"Error @ g_objPB.Create";g_objPB.Show()}catch(c){b=false,d.Log("Initialize",LOG.EXCEPTION,"",c)}return b};this.ResourceLoaded=function(a){var b=true;try{if(a==true&&g_objPB.Progress(a)==false)throw"g_objPB.onIncrease threw Error ";}catch(c){b=false,d.Log("ResourceLoaded",LOG.EXCEPTION,"",c)}return b};this.Load=function(){var a=true;try{d.ScriptFileCount=Number(files_json.length);d.ImagesCount=Number(files_json.imagescount);g_objPB.TotalCount=
d.ScriptFileCount+d.ImagesCount;var c=true;try{if(m=(files_json.seq.yahoo.css||[]).concat(files_json.seq.jquery.css||[]),m.length>0){d.Log("LoadCSSFiles",LOG.SPECIAL,"Loading CSS files in sync-mode",m.length);j=m.length;g_objScriptLoader.onLoadComplete=b;for(var e=0;e<m.length;e++)for(var g in m[e])if(g_objScriptLoader.Load(g_StaticURL+m[e][g])==false)throw"Error @ g_objScriptLoader.Load";}else if(f()==false)throw"Error @ LoadNonSeqFiles";}catch(h){c=false,d.Log("LoadCSSFiles",LOG.EXCEPTION,"",h)}if(c==
false)throw"Error @ LoadCSSFiles";}catch(k){a=false,d.Log("Load",LOG.EXCEPTION,"",k)}return a}};
var LOG={ENTRY:"ENTRY",EXIT:"EXIT",EXCEPTION:"EXCEPTION",ERROR:"ERROR",TRACE:"TRACE",SPECIAL:"SPECIAL",EVENTDATA:"EVENTDATA",EVENTLIST:"EVENTLIST",TRACKER:"TRACKER",SCORM:"SCORM",POM:"POM"},clsLoger=function(){var b=new Number(0),f=new Number(0),a,h=null,c=new Number(0),d="";this.Enable=new Boolean(false);this.LogTypes=[];this.ClassTypes=[];this.PlainLog=new Boolean(false);this.EnableAlertAtLoger=new Boolean(false);this.Initialize=function(c){try{if(this.Enable!=false)h==null&&(a=new Date,m_PrevTimeMin=
a.getMinutes(),b=a.getSeconds(),f=a.getMilliseconds(),h=window.open("about:blank")),h==null?alert("Failed to launch log window. Enable popup window"):(h.document.write(c+"<br/><br/>"),h.document.write("Log Started @ "+a.getDate()+"/"+a.getMonth()+"/"+a.getYear()+"<br/><br/>"),c="",this.PlainLog==false&&(c+='<table border=1 cellspacing=0 cellpadding=0 style="padding:3px;font-family:verdana;font-weight:normal;font-size:12px;"><tr>',c+='<td style="width:30px;padding:3px;font-weight:bold;font-size:14px;background-color:#3f3f3f;color:#FFFF00">Sl</td> ',
c+='<td style="width:100px;padding:3px;font-weight:bold;font-size:14px;background-color:#3f3f3f;color:#FFFF00">Time</td>',c+='<td style="width:300px;padding:3px;font-weight:bold;font-size:14px;background-color:#3f3f3f;color:#FFFF00">Module</td>',c+='<td style="width:300px;padding:3px;font-weight:bold;font-size:14px;background-color:#3f3f3f;color:#FFFF00">Function</td>',c+='<td style="width:300px;padding:3px;font-weight:bold;font-size:14px;background-color:#3f3f3f;color:#FFFF00">Message</td>',c+='<td style="width:300px;padding:3px;font-weight:bold;font-size:14px;background-color:#3f3f3f;color:#FFFF00">Value</td>',
c+='<td style="width:300px;padding:3px;font-weight:bold;font-size:14px;background-color:#3f3f3f;color:#FFFF00">Log Type</td>',c+='<td style="width:200px;padding:3px;font-weight:bold;font-size:14px;background-color:#3f3f3f;color:#FFFF00">Time Diff</td>',c+="</tr></table>"),h.document.write(c),d=PLAYSTATE.INITIALIZED)}catch(g){h=null,d=PLAYSTATE.NOTINITIALIZED}};this.Log=function(e,g,k,l,n){var o=e+" > "+g+"\n\n"+k+" >"+l+"\n\n"+n;try{if(this.LogTypes.length>0){var j=new Boolean(false);for(i in this.LogTypes)if(this.LogTypes[i]!=
""){if(n==this.LogTypes[i]){j=true;break}}else{j=true;break}if(j==false)return}j=false;if(this.ClassTypes.length>0){for(i in this.ClassTypes)if(this.ClassTypes[i]!=""){if(e==this.ClassTypes[i]){j=true;break}}else{j=true;break}if(j==false)return}this.EnableAlertAtLoger==true&&alert(o);if(this.Enable!=false&&d!=PLAYSTATE.NOTINITIALIZED){if(h==null)d=PLAYSTATE.NOTINITIALIZED;a=new Date;m_CurTimeMin=a.getMinutes()*6E4;m_CurTimeSec=a.getSeconds()*1E3;m_CurTimeMilSec=a.getMilliseconds();m_Curm_PrevTotal=
m_CurTimeMin+m_CurTimeSec+m_CurTimeMilSec;m_PrevTotal=m_PrevTimeMin*6E4+b*1E3+f;m_CurTime=a.getHours()+":"+a.getMinutes()+":"+a.getSeconds()+"."+a.getMilliseconds();m_TimeDiff=m_Curm_PrevTotal-m_PrevTotal;e==""&&(e+="&nbsp;");g==""&&(g+="&nbsp;");k==""&&(k+="&nbsp;");l==""&&(l+="&nbsp;");m_fontcolor="#000000";m_logtype=n.toLowerCase();switch(n){case LOG.ENTRY:m_logtype="fn-start";m_fontcolor="#FF00FF";break;case LOG.EXIT:m_logtype="fn-exit";m_fontcolor="#00FF00";break;case LOG.EXCEPTION:m_logtype=
"exception";m_fontcolor="#ff0000";break;case LOG.TRACE:m_logtype="trace";m_fontcolor="#0000ff";break;case LOG.ERROR:m_logtype="custom-error";m_fontcolor="maroon";break;case LOG.POM:m_logtype="POM",m_fontcolor="purple"}m_tmpData='<table border=1 style="padding:3px;font-family:verdana;font-weight:normal;font-size:12px;">';this.PlainLog==false?(m_tmpData+="<tr>",m_tmpData+='<td style="width:30px;padding:3px;">'+ ++c+"</td> ",m_tmpData+='<td style="width:100px;padding:3px;">'+m_CurTime+"</td>",m_tmpData+=
'<td style="width:300px;padding:3px;">'+e+"</td>",m_tmpData+='<td style="width:300px;padding:3px;">'+g+"</td>",m_tmpData+='<td style="width:300px;padding:3px;color:'+m_fontcolor+'">'+k+"</td>",m_tmpData+='<td style="width:300px;padding:3px;color:'+m_fontcolor+'">'+l+"</td>",m_tmpData+='<td style="width:300px;padding:3px;color:'+m_fontcolor+'">'+m_logtype+"</td>",m_tmpData+='<td style="width:200px;padding:3px;">  [ '+m_TimeDiff+" ] </td>",m_tmpData+="</tr>"):(m_tmpData+="<hr/>",m_tmpData+='<span style="width:30px;padding:3px;">'+
++c+"</span><br/>",m_tmpData+='<span style="width:100px;padding:3px;">'+m_CurTime+"</span><br/>",m_tmpData+='<span style="width:300px;padding:3px;">'+e+"</span><br/>",m_tmpData+='<span style="width:300px;padding:3px;">'+g+"</span><br/>",m_tmpData+='<span style="width:300px;padding:3px;color:'+m_fontcolor+'">'+k+"</span><br/>",m_tmpData+='<span style="width:300px;padding:3px;color:'+m_fontcolor+'">'+l+"</span><br/>",m_tmpData+='<span style="width:300px;padding:3px;color:'+m_fontcolor+'">'+m_logtype+
"</span><br/>",m_tmpData+='<span style="width:200px;padding:3px;">  [ '+m_TimeDiff+" ] </span><br/>",m_tmpData+="<hr/>");m_tmpData+="</table>";h.document!=null&&h.document.write(m_tmpData);m_PrevTimeMin=a.getMinutes();b=a.getSeconds();f=a.getMilliseconds()}}catch(p){d=PLAYSTATE.NOTINITIALIZED}}};
clsProgressBar=function(){clsPlayerBase.call(this,"clsProgressBar");var b=this,f,a,h=null;this.Height=this.Width=this.Top=this.Left="";this.CurrentCount=this.TotalCount=0;this.Reset=function(){try{f.style.width="0%",b.CurrentCount=0}catch(a){b.Log("Reset",LOG.EXCEPTION,"",a)}};this.Create=function(c,d,e,g){try{var k="5px",l="5px",n="#207ce5",o="";if(e!=void 0&&e!=null){if(e.css.br!=void 0)k=e.css.br;if(e.css.pd!=void 0)l=e.css.pd;if(e.css.fc!=void 0)n=e.css.fc;e.css.bw!=void 0&&e.css.bs!=void 0&&
e.css.bc!=void 0&&(border=e.css.bw+" "+e.css.bs+" "+e.css.bc);if(e.css.bg!=void 0)o=e.css.bg}h=d;var j=b.CreateHTMLElement("DIV");j.style.display="none";j.style.visibility="visible";j.style.border="1px solid #207ce5";j.style.borderRadius=k;j.style.overflowY="hidden";j.style.left=b.Left;j.style.width=b.Width;j.style.position="absolute";j.style.top=b.Top;j.style.height=b.Height;j.style.padding=l;j.style.overflowX="hidden";j.style.backgroundColor=o;c.appendChild(j);a=document.getElementById(j.id);var p=
b.GetUniqueID();a.innerHTML="<table border=0 width=100% height=100% style='border-spacing:0px;padding:0px;'><tr><td align="+g+" valign=center id='"+p+"' style='padding:0px;'></td></tr></table>";var m=b.CreateHTMLElement("DIV");m.style.display=g_inline;m.style.position="relative";m.style.visibility="visible";m.style.backgroundColor=n;m.style.color="white";m.style.fontWeight="bold";m.style.borderRadius=k;m.style.height="100%";m.style.width="0px";document.getElementById(p).appendChild(m);f=document.getElementById(m.id)}catch(q){b.Log("Create",
LOG.EXCEPTION,"",q)}};this.SetMessage=function(a){try{if(h!=null)h.innerHTML=a}catch(d){b.Log("SetMessage",LOG.EXCEPTION,"",d)}};this.SetValue=function(a){try{if(a>100&&(a=100),f!=void 0)f.style.width=a+"%"}catch(d){b.Log("SetMessage",LOG.EXCEPTION,"",d)}};this.Hide=function(){try{a.style.display="none",h.style.display="none"}catch(c){b.Log("Hide",LOG.EXCEPTION,"",c)}};this.Show=function(){try{a.style.display=g_inline,h.style.display=g_inline}catch(c){b.Log("Hide",LOG.EXCEPTION,"",c)}};this.Progress=
function(a){try{if(a==true){b.CurrentCount++;var d=b.CurrentCount/b.TotalCount*100;d>100&&(d=100);f.innerHTML=Math.round(d,0)+"%";f.style.width=d+"%"}}catch(e){b.Log("Progress",LOG.EXCEPTION,"",e)}}};
clsScriptLoader=function(){function b(a,b){var g=true;try{b=b||this,b.onerror=null,c.Log("ImgCSSLoaded",LOG.TRACE,"File = ",b.src),f(a,b)}catch(h){g=false,c.Log("ImgCSSLoaded",LOG.EXCEPTION,"",h)}if(c.onLoadComplete!=null)c.onLoadComplete(g)}function f(a,b){var f=true,h=false;try{var l=false,l=BROWSER.LEGACY==true?b.Loaded:this.Loaded;l==false?(BROWSER.LEGACY==true?b.Loaded=true:this.Loaded=true,b=b||this,c.FileName=b.attributes.src?b.attributes.src.value:b.attributes.href.value,c.Log("ScriptLoaded",
LOG.TRACE,"File = ",c.FileName)):h=true}catch(n){f=false,c.Log("ScriptLoaded",LOG.EXCEPTION,"",n)}if(h==false&&c.onLoadComplete!=null)c.onLoadComplete(f)}function a(){var a=true;try{if(this.readyState=="loaded"||this.readyState=="complete")this.onreadystatechange=null,f("loaded",this)}catch(b){this.onreadystatechange=null,a=false,c.Log("ScriptOnReadyStateChange",LOG.EXCEPTION,"",b)}if(a==false&&c.onLoadComplete!=null)c.onLoadComplete(false)}function h(){var a=true;try{if(c.FileName=this.attributes.src?
this.attributes.src.value:this.attributes.href.value,c.Log("ScriptLoaded",LOG.EXCEPTION,"File not Loaded ? ",c.FileName),c.onLoadComplete!=null)c.onLoadComplete(false)}catch(b){a=false,c.Log("ScriptOnError",LOG.EXCEPTION,"",b)}if(a==false&&c.onLoadComplete!=null)c.onLoadComplete(false)}clsPlayerBase.call(this,"clsScriptLoader");this.FileName="";var c=this;this.Load=function(d){var e=true;try{if(c.onLoadComplete==null)throw"onLoadComplete = null";if(d==void 0)throw"sURL = undefined";var g=null,k=d.split(".").pop();
switch(k){case "js":g=document.createElement("SCRIPT");g.async=true;g.type="text/javascript";g.src=d;break;case "css":g=document.createElement("LINK");g.type="text/css";g.rel="stylesheet";g.src=d;g.href=d;break;default:throw k+" is not of excpected file type";}g.Loaded=false;BROWSER.LEGACY==true?g.onreadystatechange=a:g.onload=f;g.onerror=h;if(BROWSER.SAFARI&&k==="css"){g.onreadystatechange=null;g.onload=null;g.onerror=null;var l=document.createElement("img");l.onerror=b;l.src=d;l.Loaded=false}var n=
document.getElementsByTagName("HEAD");n[0]!=null&&n[0].appendChild(g)}catch(o){e=false,c.Log("Load",LOG.EXCEPTION,d,o)}return e}};
